# Tab management
map ctrl+a>c new_tab
map ctrl+a>shift+7 close_tab
map ctrl+a>, set_tab_title " "
map ctrl+a>p previous_tab
map ctrl+a>n next_tab
# go to previously active tab
map ctrl+a>l goto_tab 0 
map ctrl+a>1 goto_tab 1
map ctrl+a>2 goto_tab 2
map ctrl+a>3 goto_tab 3
map ctrl+a>4 goto_tab 4
map ctrl+a>5 goto_tab 5
map ctrl+a>6 goto_tab 6
map ctrl+a>7 goto_tab 7
map ctrl+a>8 goto_tab 8
map ctrl+a>9 goto_tab 9
map ctrl+a>shift+. move_tab_forward
map ctrl+a>shift+, move_tab_backward

# Window management
map ctrl+a>shift+5 launch --location=hsplit
map ctrl+a>shift+- launch --location=hsplit 
# apostrophe
map ctrl+a>shift+0x27 launch --location=vsplit
map ctrl+a>shift+\ launch --location=vsplit
map ctrl+a>; nth_window -1
map ctrl+a>shift+[ move_window_backward
map ctrl+a>shift+] move_window_forward
map ctrl+a>h neighboring_window left
map ctrl+a>left neighboring_window left
map ctrl+a>j neighboring_window down
map ctrl+a>down neighboring_window down
map ctrl+a>k neighboring_window up
map ctrl+a>up neighboring_window up
map ctrl+a>l neighboring_window right
map ctrl+a>right neighboring_window right
map ctrl+a>space next_layout
map ctrl+a>z toggle_layout stack
map ctrl+a>q focus_visible_window
