[general]
import = ["/home/jason/.config/alacritty/dracula.toml"]

[cursor]
style = "Beam"
vi_mode_style = "Block"

[font]
size = 10

[font.normal]
family = "Hasklug Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
# decorations = "None"
dynamic_title = true
title = "Alacritty"
# startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 5
