set-option -g default-terminal "screen-256color"
set -as terminal-features ",alacritty*:RGB"

# These shouldn't be needed because $EDITOR is vim but for safety
setw -g mode-keys vi

set -g mouse on

set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

# Dracula theme configuration
set -g @dracula-plugins 'battery network weather time'
set -g @dracula-show-powerline true
set -g @dracula-time-format "%F %R%z"
set -g @dracula-show-location false

# Run tpm. Needs to be at bottom of config
run '~/.config/tmux/plugins/tpm/tpm'

